### ISSUE TITLE
Nuspec copy/paste issue

### ISSUE THREAD

**Issue by gluck** [RolandPheasant/DynamicData.ReactiveUI#2]
target file for nuspec is DynamicData.dll, instead of DD.RxUI.dll.

hint: only specify target folder to avoid this.

Also (strangely) the nupkg contains both DD.dll _and_ DD.RxUI.dll, in different folders, probably not working well.

Cheers.

**Comment by RolandPheasant** [comment]
Funny thing is I checked out the pkg on dynamic trader (my demo project) and as far as I could see it installed the correct files.

I will check again tomorrow

**Comment by RolandPheasant** [comment]
I changed the nuspec file and there is no phantom file in the pack now.Cheers
