### ISSUE TITLE
Bind to ReactiveList can destroy further DisposeMany/OnItemRemoved

### ISSUE THREAD

**Issue by StefanDoubleU** [RolandPheasant/DynamicData.ReactiveUI#5]
Under some circumstances, it happens that after Bind() the OnItemRemoved is not getting called.
I wasn't able to get any differences when it happens and when its working. (have two similar places I use it)

With ObservableCollectionExtended, everything work as expected. 

``` C#
var sc = new SourceCache<int, int>(i => i.GetHashCode());
var rl = new ReactiveList<int>();

sc.Connect()
   .OnItemRemoved(model => Logger.Info("removed"))
   .Bind(rl)
   .OnItemRemoved(model => Logger.Info("removed after"))
   .DisposeMany()
   .Subscribe()
```

**Comment by StefanDoubleU** [comment]
ObserveOnDispatcher() fixes the issue.
OnItemRemoved is only getting called if Bind is already on the dispatcher, which is recommended anyway.

But, is it really good, that DisposeMany is depended on the Scheduler?

**Comment by RolandPheasant** [comment]
Have you tried subscribing to exceptions?

**Comment by RolandPheasant** [comment]
Dynamic data is scheduler agnostic

**Comment by StefanDoubleU** [comment]
Unfortunately, everything looks fine in the first place. Even the binding works.

**Comment by RolandPheasant** [comment]
It could be a thread exception
